config/routes.rb
Rails.application.routes.draw do
  resources :requests, only: [:index, :new, :create]

  root 'requests#new'
end

app/models/answer_object.rb
class AnswerObject
  include ActiveModel::Model

  attr_accessor(:status,
                :data,
                :offers,
                :raw_data,
                :sign,
                :sign_check)

  def offers
    @offers ||= begin
                  if data.has_key?('offers')
                    data['offers'].map { |offer| Offer.new(offer) }
                  else
                    []
                  end
                end
  end

  def ok?
    data['code'] == 'ok'
  end

  def valid_sign?
    sign == sign_check
  end

  def message
    data['message']
  end

  def offers_count
    offers.count
  end

  def pages
    data['pages']
  end

  def data
    @data ||= ActiveSupport::JSON.decode raw_data
  end
end

app/models/offer.rb
class Offer
  include ActiveModel::Model

  attr_accessor(:link,
                :title,
                :offer_id,
                :teaser,
                :required_actions,
                :thumbnail,
                :offer_types,
                :payout,
                :time_to_payout,
                :store_id)
end

app/models/request_object.rb
class RequestObject
  include ActiveModel::Model

  attr_accessor(:appid,
                :device_id,
                :locale,
                :ip,
                :offer_types,
                :uid,
                :page,
                :pub0,
                :ps_time,
                :timestamp)

  def initialize(*args)
    # I leave it here becuase: > 4. Note:design for only having one app/appID.
    @locale = :de
    @timestamp = DateTime.now.to_i
    @appid = 157
    @device_id = '2b6f0cc904d137be2e1730235f5664094b83'
    @ip = '109.235.143.113'
    @offer_types = 112

    super
  end

  def to_h
    h = {
      appid: appid,
      device_id: device_id,
      locale: locale,
      ip: ip,
      offer_types: offer_types,
      uid: uid,
      page: page,
      pub0: pub0,
      ps_time: ps_time,
      timestamp: timestamp
    }
    h.delete_if { |k, v| v.blank? }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  helper_method :request_form

  def new

  end

  def index
    render :new
  end

  def create
    @request_form = RequestForm.new(params[:request_form])

    if @request_form.valid?
      request_object = RequestObject.new({
        pub0: @request_form.pub0,
        page: @request_form.page,
        uid: @request_form.uid
      })
      service = OfferApiRequestService.new(request_object)
      @answer = service.call
      Rails.logger.debug @answer.status
      Rails.logger.debug @answer.data
    end

    render :new
  end

  private

  def request_form
    @request_form ||= RequestForm.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
  title FyberDeveloperChallenge
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags
body
  .container
    = yield

app/views/requests/_form.html.slim
= form_for request_form, url: requests_path do |f|
  h3 Request Form

  .form-group class=('has-error' if request_form.errors.include?(:uid))
    = f.label :uid
    = f.text_field :uid, class: 'form-control'
    - request_form.errors.full_messages_for(:uid).each do |message|
      span.help-block = message

  .form-group class=('has-error' if request_form.errors.include?(:pub0))
    = f.label :pub0
    = f.text_field :pub0, class: 'form-control'
    - request_form.errors.full_messages_for(:pub0).each do |message|
      span.help-block = message

  .form-group class=('has-error' if request_form.errors.include?(:page))
    = f.label :page
    = f.number_field :page, class: 'form-control'
    - request_form.errors.full_messages_for(:page).each do |message|
      span.help-block = message

  = f.submit 'Request', class: 'btn btn-default'

app/views/requests/_offer.html.slim
.offer-row
  .media
    .media-left.pull-left
      a href=offer.link
        img.media-object src=offer.thumbnail['lowres']
    .media-body
      h4.media-heading = offer.title
      = offer.payout

app/views/requests/new.html.slim
.row
  .col-md-6.col-md-offset-2
    = render partial: 'form'
  - if defined? @answer
    .col-md-6.col-md-offset-2
      - if !@answer.ok?
        h3 Offers
        .help-block
          ' Found:
          => @answer.offers_count
          '. Pages:
          => @answer.pages
          '. Sign valid:
          = @answer.valid_sign?
        = render partial: 'offer', collection: @answer.offers
        - if @answer.offers_count == 0
          h4 No offers available
      - else
        h3 Something happened
        = @answer.message